# Generated by Django 5.2 on 2025-04-26 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("libros", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="autor",
            name="fecha_nacimiento",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="libro",
            name="fecha_publicacion",
            field=models.DateField(blank=True, null=True),
        ),
    ]
